Update functions calls to be delegated
alastria/alastria-identity-lib pull request #133
Opened 2020-10-16 11:34 UTC by DrankoLQ

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Documentation

## Description
This PR updates some functions calls to be delegated so they can go through the proxy

2020-10-20 12:42 UTC, DrankoLQ commented
A question @VictorNS69: is it supposed to fail some examples with this change? Correct me if I'm wrong, but the delegated calls is used with upgradeable smart contracts only and we don't have them yet, isn't it?

2020-10-20 12:57 UTC, VictorNS69 commented
> A question @VictorNS69: is it supposed to fail some examples with this change? Correct me if I'm wrong, but the delegated calls are used with upgradeable smart contracts only and we don't have them yet, isn't it?

1) Some examples will fail if you use them in the wrong order. For example, if you try to delete an Issuer that does not have an issuer role. However, if the error is something like "invalid RPC call", "invalid arguments", etc it means something is not working. **If you have any specific errors, just show me the log**
2) **Delegated calls are used in both contracts**, upgradeable and non-upgradeable. **You should test with the non-upgradeable version (master)** because the upgradeable version is not working at the moment. See #116

2020-10-23 11:00 UTC, VictorNS69 commented
@DrankoLQ I recomend you to print `delegatedData` and `transaction.data`. The values should be close to `0x889776a80000000000000000000000004b750a9a228afbcc97aa9e0ac967b0da9aab2f1b0000000000000000000000000000000000000000000000000000000000000003` for `delegatedData` and `0x597b2e9b00000000000000000000000061087480e211aefa69a103a28a34844a41eeb380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044889776a80000000000000000000000004b750a9a228afbcc97aa9e0ac967b0da9aab2f1b000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000` for `transaction.data`.

**At least the begining of each hex should be the same I think.**

2020-10-30 09:04 UTC, DrankoLQ commented
I have tested the example in the right order and everything works @VictorNS69  🙂

2020-11-06 12:16 UTC, VictorNS69 commented on src/txFactory/identityManagerTransactionFactory.ts
> +  transaction.data = delegated(web3, delegatedData)
In a call function (getters) there is no need to use the proxy. Revert this function.

2020-11-06 12:18 UTC, VictorNS69 requested changes

2020-11-06 12:18 UTC, VictorNS69 commented on src/txFactory/identityManagerTransactionFactory.ts
> +  transaction.data = delegated(web3, delegatedData)
In a call function (getters) there is no need to use the proxy. Revert this function.

2020-11-06 12:24 UTC, VictorNS69 commented
The rest is working properly

2020-11-10 08:11 UTC, VictorNS69 approved these changes

2020-11-10 08:11 UTC, merged